version: '3.8'

services:
  node1:
    build: ./node-app
    container_name: node1
    hostname: node1
    privileged: true
    networks:
      gluster:
        ipv4_address: 10.10.10.2

  node2:
    build: ./node-app
    container_name: node2
    hostname: node2
    privileged: true
    networks:
      gluster:
        ipv4_address: 10.10.10.3

  node3:
    build: ./node-app
    container_name: node3
    hostname: node3
    privileged: true
    networks:
      gluster:
        ipv4_address: 10.10.10.4

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node1
      - node2
      - node3
    networks:
      gluster:
        ipv4_address: 10.10.10.5

networks:
  gluster:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
